[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "whole_body_controller"
version = "0.2.0"
description = "Stability-aware controller for Unitree Go2"
dependencies = [
    "numpy",
    "matplotlib",
    "pygame",
    "mujoco"
]

[tool.hatch.build.targets.wheel]
packages = [
    "py_src/control",
    "py_src/data_structures",
    "py_src/hardware_abstraction_layer",
    "py_src/interpolation",
    "py_src/kinematics"
]

[project.scripts]
run-dog   = "main:main"
visualise = "visualisation.main:main"
test-ik   = "visualisation.graph_angle:main"
