import numpy as np
import numpy.typing as npt
from data_structures.points import Point3D, PointList
from typing import override
from . import Interpolator

# TODO: add float alpha (used for time stepping)
# TODO: add bool inital_momentum (use first and last point as ghost points)
# TODO: May need to implement in C++ to optimise
# Ghost points determine the overall tangent of the curve (and thus the tangent of each segment).
# Knots are points the curve must hit.
# Interpolated points are points generated by the interpolator in between the knots.
class CatmullRomSpline(Interpolator):
    def linear_interpolation(self, t:float, point_prev:Point3D, t_prev:float, point_next:Point3D, t_next:float) -> Point3D:
        delta_t = (t_next - t_prev)  # Change in time
        weight_prev = (t_next - t) / delta_t
        weight_next = (t - t_prev) / delta_t

        return (weight_prev * point_prev) + (weight_next * point_next)

    def barry_goldman_pyramid(self, t:float, windowed_t_values:npt.NDArray[np.float64],  windowed_points:PointList) -> Point3D:
        if len(windowed_t_values) != 4:
            raise IndexError(f"{{windowed_t_values}} must be of length 4! (length: {len(windowed_t_values)})")
        if len(windowed_points) != 4:
            raise IndexError(f"{{windowed_points}} must be of length 4! (length: {len(windowed_points)})")

        # Linear (Tier 1)
        a_1 = self.linear_interpolation(t, windowed_points[0], windowed_t_values[0], windowed_points[1], windowed_t_values[1])
        a_2 = self.linear_interpolation(t, windowed_points[1], windowed_t_values[1], windowed_points[2], windowed_t_values[2])
        a_3 = self.linear_interpolation(t, windowed_points[2], windowed_t_values[2], windowed_points[3], windowed_t_values[3])

        # Parabolic (Tier 2) 
        b_1 = self.linear_interpolation(t, a_1, windowed_t_values[0], a_2, windowed_t_values[2])
        b_2 = self.linear_interpolation(t, a_2, windowed_t_values[1], a_3, windowed_t_values[3])

        # Cubic (Tier 3)
        c = self.linear_interpolation(t, b_1, windowed_t_values[1], b_2, windowed_t_values[2])
        return c

    def get_time(self):
        pass

    # TODO: optimise window search
    def get_active_window(self, t:float, t_values:npt.NDArray[np.float64],  points:PointList):
        if len(t_values) != len(points):
            raise IndexError(f"Length mismatch between {{t_values}} and {{points}}! ({len(t_values)} != {len(points)})")
       
        # Find active window/curve segment
        index_knot_prev = len(t_values) - 1
        for i, knot_time in enumerate(t_values):
            if knot_time > t:
                index_knot_prev = i - 1
                break
        print(index_knot_prev)

        # Establish window frame
        windowed_t_values:npt.NDArray[np.float64] = np.empty(4)
        windowed_points:PointList = np.empty((4, 3))

        src_start = index_knot_prev - 1
        src_end   = src_start + 3

        dest_start = 0
        dest_end   = 3

        #     Reuse first element for Ghost point
        if src_start < 0:
            src_end -= (src_start + 1)  # Realign end
            src_start = 0
            windowed_t_values[dest_start] = t_values[src_start]
            windowed_points[dest_start]   = points[src_start]
            dest_start += 1

        #     Reuse last element for Ghost point
        if src_end > len(t_values):
            src_end = len(t_values) - 1
            windowed_t_values[dest_end] = t_values[src_end]
            windowed_points[dest_end]   = points[src_end]
            dest_end -= 1

        print(f"Window:\n\tsrc_start = {src_start}\n\tsrc_end = {src_end}\n\tdest_start = {dest_start}\n\tdest_end = {dest_end}")  # TODO: Remove, for debugging

        print(f"\tRaw: {repr(t_values)}\n\tRanged: {repr(t_values[src_start:src_end])}")  # TODO: Remove, for debugging

        # Finish loading window
        windowed_t_values[dest_start:dest_end] = t_values[src_start:src_end]
        windowed_points[dest_start:dest_end]   = points[src_start:src_end]

        print(f"\n\tt_values = {repr(windowed_t_values)}\n\tpoints = {repr(windowed_points)}")  # TODO: Remove, for debugging
        return (windowed_t_values, windowed_points)

    # TODO: rename control points to knots for accuracy.
    @override
    def interpolate_point(self, t:float|np.float64, t_values:npt.NDArray[np.float64], control_points:PointList) -> Point3D:
        print(f"interpolate_point(\n\tt = {t},\n\tt_values = {repr(t_values)},\n\tcontrol_points = {repr(control_points)}\n);")  # TODO: Remove, for debugging
        windowed_t_values, windowed_points = self.get_active_window(t, t_values, control_points)

        return self.barry_goldman_pyramid(t, windowed_t_values, windowed_points)