import math
import numpy as np
import numpy.typing as npt
from data_structures.points import Point3D, PointList
from typing import override
from . import Interpolator

# TODO: add float alpha (used for time stepping)
# TODO: add bool inital_momentum (use first and last point as ghost points)
# TODO: May need to implement in C++ to optimise
# Ghost points determine the overall tangent of the curve (and thus the tangent of each segment).
# Knots are points the curve must hit.
# Interpolated points are points generated by the interpolator in between the knots.
class CatmullRomSpline(Interpolator):
    # TODO: Add comment
    def __init__(self, alpha=0.5, pre_phantom_point=None, post_phantom_point=None):
        self.alpha = alpha
        self.pre_phantom_point = pre_phantom_point
        self.post_phantom_point = post_phantom_point

    def linear_interpolation(self, t:float, point_prev:Point3D, t_prev:float, point_next:Point3D, t_next:float) -> Point3D:
        delta_t = (t_next - t_prev)  # Change in time
        weight_prev = (t_next - t) / delta_t
        weight_next = (t - t_prev) / delta_t

        return (weight_prev * point_prev) + (weight_next * point_next)

    def barry_goldman_pyramid(self, t:float, windowed_t_anchors:npt.NDArray[np.float64],  windowed_points:PointList) -> Point3D:
        if len(windowed_t_anchors) != 4:
            raise IndexError(f"{{windowed_t_anchors}} must be of length 4! (length: {len(windowed_t_anchors)})")
        if len(windowed_points) != 4:
            raise IndexError(f"{{windowed_points}} must be of length 4! (length: {len(windowed_points)})")

        # Linear (Tier 1)
        a_1 = self.linear_interpolation(t, windowed_points[0], windowed_t_anchors[0], windowed_points[1], windowed_t_anchors[1])
        a_2 = self.linear_interpolation(t, windowed_points[1], windowed_t_anchors[1], windowed_points[2], windowed_t_anchors[2])
        a_3 = self.linear_interpolation(t, windowed_points[2], windowed_t_anchors[2], windowed_points[3], windowed_t_anchors[3])

        # Parabolic (Tier 2) 
        b_1 = self.linear_interpolation(t, a_1, windowed_t_anchors[0], a_2, windowed_t_anchors[2])
        b_2 = self.linear_interpolation(t, a_2, windowed_t_anchors[1], a_3, windowed_t_anchors[3])

        # Cubic (Tier 3)
        c = self.linear_interpolation(t, b_1, windowed_t_anchors[1], b_2, windowed_t_anchors[2])
        # print(f"C {{{t}}} dt: {(windowed_t_anchors[2] - windowed_t_anchors[1])} ({windowed_t_anchors[2]} - {windowed_t_anchors[1]})")  # TODO: Remove, for debugging
        return c

    def get_active_window(self, t:float, t_anchors:npt.NDArray[np.float64],  points:PointList):
        if len(t_anchors) != len(points):
            raise IndexError(f"Length mismatch between {{t_anchors}} and {{points}}! ({len(t_anchors)} != {len(points)})")
       
        # Find active window/curve segment
        idx = np.searchsorted(t_anchors, t) - 1     # Find index of previous knot
        idx = max(0, min(idx, len(t_anchors) - 2))  # Clamp index

        # Pre-allocate the window
        windowed_t_anchors:npt.NDArray[np.float64] = np.empty(4)
        windowed_points:PointList = np.empty((4, 3))

        # Calculate copy ranges
        src_start = idx - 1
        src_end   = idx + 3  # 4 elements
        dest_start = 0
        dest_end   = 4  # Exclusive stop

        # Handle Start Boundary
        if src_start < 0:
            windowed_t_anchors[0] = t_anchors[0] - (t_anchors[1] - t_anchors[0])  # Extrapolate backwards
            windowed_points[0]   = points[0]
            dest_start = 1
            src_start  = 0

        # Handle End Boundary
        if src_end > len(t_anchors):
            windowed_t_anchors[3] = t_anchors[-1] + (t_anchors[-1] - t_anchors[-2])  # Extrapolate forwards
            windowed_points[3]   = points[-1]
            dest_end = 3
            src_end  = len(t_anchors)  # Exclusive stop

        # print(f"Window:\n\tsrc_start = {src_start}\n\tsrc_end = {src_end}\n\tdest_start = {dest_start}\n\tdest_end = {dest_end}")  # TODO: Remove, for debugging
        # print(f"\tRaw: {repr(t_anchors)}\n\tRanged: {repr(t_anchors[src_start:src_end])}")  # TODO: Remove, for debugging

        # Finish loading window
        windowed_t_anchors[dest_start:dest_end] = t_anchors[src_start:src_end]
        windowed_points[dest_start:dest_end]   = points[src_start:src_end]

        # print(f"\n\tt_anchors = {repr(windowed_t_anchors)}\n\tpoints = {repr(windowed_points)}")  # TODO: Remove, for debugging
        return (windowed_t_anchors, windowed_points)

    @override
    def interpolate_point(self, t:float, t_anchors:npt.NDArray[np.float64], control_points:PointList) -> Point3D:
        # print(f"interpolate_point(\n\tt = {t},\n\tt_anchors = {repr(t_anchors)},\n\tcontrol_points = {repr(control_points)}\n);")  # TODO: Remove, for debugging
        windowed_t_anchors, windowed_points = self.get_active_window(t, t_anchors, control_points)

        return self.barry_goldman_pyramid(t, windowed_t_anchors, windowed_points)
    
    def get_time(self, point:Point3D, point_prev:Point3D, t_prev:float) -> float:
        distance = math.sqrt(
            (point[0] - point_prev[0])**2 +
            (point[1] - point_prev[1])**2 +
            (point[2] - point_prev[2])**2
        )

        return distance**self.alpha + t_prev

    @override
    def calculate_time_anchors(self, control_points: PointList) -> npt.NDArray[np.float64]:
        if self.pre_phantom_point == None:  # Extrapolate backwards
            self.pre_phantom_point = control_points[0] - (control_points[1] - control_points[0])
        if self.post_phantom_point == None:  # Extrapolate forwards
            self.post_phantom_point = control_points[-1] + (control_points[-1] - control_points[-2])

        t_anchors:npt.NDArray[np.float64] = np.empty(len(control_points))
        t_anchors[0] = 0.0

        point_prev = self.pre_phantom_point
        for i in range(1, len(control_points)):
            t_anchors[i] = self.get_time(control_points[i], point_prev, t_anchors[i-1])
            point_prev = control_points[i]
        
        return t_anchors