import numpy as np
import numpy.typing as npt
from data_structures.points import Point3D, PointList
from typing import override
from . import Interpolator

# TODO: add float alpha (used for time stepping)
# TODO: add bool inital_momentum (use first and last point as ghost points)
# TODO: May need to implement in C++ to optimise
# Ghost points determine the overall tangent of the curve (and thus the tangent of each segment).
# Knots are points the curve must hit.
# Interpolated points are points generated by the interpolator in between the knots.
class CatmullRomSpline(Interpolator):
    def linear_interpolation(self, t:float, point_prev:Point3D, t_prev:float, point_next:Point3D, t_next:float) -> Point3D:
        delta_t = (t_next - t_prev)  # Change in time
        weight_prev = (t_next - t) / delta_t
        weight_next = (t - t_prev) / delta_t

        return (weight_prev * point_prev) + (weight_next * point_next)

    def barry_goldman_pyramid(self, t:float, windowed_t_values:npt.NDArray[np.float64],  windowed_points:PointList) -> Point3D:
        if len(windowed_t_values) != 4:
            raise IndexError(f"{{windowed_t_values}} must be of length 4! (length: {len(windowed_t_values)})")
        if len(windowed_points) != 4:
            raise IndexError(f"{{windowed_points}} must be of length 4! (length: {len(windowed_points)})")

        # Linear (Tier 1)
        a_1 = self.linear_interpolation(t, windowed_points[0], windowed_t_values[0], windowed_points[1], windowed_t_values[1])
        a_2 = self.linear_interpolation(t, windowed_points[1], windowed_t_values[1], windowed_points[2], windowed_t_values[2])
        a_3 = self.linear_interpolation(t, windowed_points[2], windowed_t_values[2], windowed_points[3], windowed_t_values[3])

        # Parabolic (Tier 2) 
        b_1 = self.linear_interpolation(t, a_1, windowed_t_values[0], a_2, windowed_t_values[2])
        b_2 = self.linear_interpolation(t, a_2, windowed_t_values[1], a_3, windowed_t_values[3])

        # Cubic (Tier 3)
        c = self.linear_interpolation(t, b_1, windowed_t_values[1], b_2, windowed_t_values[2])
        return c

    def get_time(self):
        pass

    # TODO: optimise window search
    def get_active_window(self, t:float, t_values:npt.NDArray[np.float64],  points:PointList):
        # Find active window/curve segment
        index_knot_prev = -1
        for i, knot_time in enumerate(t_values):
            if knot_time > t:
                index_knot_prev = i - 1
                break
        
        # Establish window frame
        w_start = index_knot_prev - 1
        w_end   = w_start + 4

        # Get window
        windowed_t_values:npt.NDArray[np.float64] = t_values[w_start:w_end]
        windowed_points:PointList = points[w_start:w_end]
        return (windowed_t_values, windowed_points)

    # TODO: rename control points to knots for accuracy.
    @override
    def interpolate_point(self, t:float|np.float64, t_values:npt.NDArray[np.float64], control_points:PointList) -> Point3D:
        windowed_t_values, windowed_points = self.get_active_window(t, t_values, control_points)

        return self.barry_goldman_pyramid(t, windowed_t_values, windowed_points)